# Generated by Django 3.2.13 on 2022-05-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customopeninghours',
            options={'verbose_name': 'Niestandardowe Godziny Otwarcia', 'verbose_name_plural': 'Niestandardowe Godziny Otwarcia'},
        ),
        migrations.AlterModelOptions(
            name='historicalcustomopeninghours',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Niestandardowe Godziny Otwarcia'},
        ),
        migrations.AlterModelOptions(
            name='historicalopeninghours',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Godziny Otwarcia'},
        ),
        migrations.AlterModelOptions(
            name='historicalplace',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Lokal'},
        ),
        migrations.AlterModelOptions(
            name='openinghours',
            options={'verbose_name': 'Godziny Otwarcia', 'verbose_name_plural': 'Godziny Otwarcia'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Lokal', 'verbose_name_plural': 'Lokale'},
        ),
    ]
