# Generated by Django 3.2.13 on 2022-06-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20220527_0937'),
        ('places', '0002_auto_20220528_1702'),
    ]

    operations = [
    ]
