# Generated by Django 3.2.13 on 2022-06-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20220603_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalopeninghours',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalopeninghours',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
