# Generated by Django 3.2.13 on 2022-06-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20220604_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalopeninghours',
            name='end_time',
            field=models.TimeField(blank=True, default='00:00:00.000000', null=True),
        ),
        migrations.AlterField(
            model_name='historicalopeninghours',
            name='start_time',
            field=models.TimeField(blank=True, default='00:00:00.000000', null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='end_time',
            field=models.TimeField(blank=True, default='00:00:00.000000', null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='start_time',
            field=models.TimeField(blank=True, default='00:00:00.000000', null=True),
        ),
    ]
