# Generated by Django 3.2.13 on 2022-06-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_merge_0002_auto_20220527_0937_0002_auto_20220528_1702'),
        ('places', '0005_auto_20220604_2305'),
    ]

    operations = [
    ]
