# Generated by Django 3.2.13 on 2022-07-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_merge_20220610_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplace',
            name='cloud_id',
            field=models.CharField(default=321728883, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalplace',
            name='refresh_token',
            field=models.CharField(default='cbeffa56eda5ad859d3d97f6ae645f5a', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='cloud_id',
            field=models.CharField(default=321728883, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='refresh_token',
            field=models.CharField(default='cbeffa56eda5ad859d3d97f6ae645f5a', max_length=256),
            preserve_default=False,
        ),
    ]
