# Generated by Django 3.2.13 on 2022-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20220712_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplace',
            name='cloud_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplace',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='cloud_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
