# Generated by Django 3.2.13 on 2022-05-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220523_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclientaddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclientaddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
