# Generated by Django 3.2.13 on 2022-05-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220524_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaddress',
            name='address_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='surname',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalclientaddress',
            name='address_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalclientaddress',
            name='surname',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
