# Generated by Django 3.2.13 on 2022-06-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220524_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaddress',
            name='phone_number',
            field=models.CharField(default='123456789', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalclientaddress',
            name='phone_number',
            field=models.CharField(default='123456789', max_length=16),
            preserve_default=False,
        ),
    ]
