# Generated by Django 3.2.13 on 2022-09-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Święta',
                'verbose_name_plural': 'Święta',
            },
        ),
    ]
