# Generated by Django 3.2.13 on 2022-06-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220601_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvariant',
            name='group',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='group',
        ),
    ]
