# Generated by Django 3.2.13 on 2022-06-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20220608_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvariant',
            old_name='group_temp2',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='group_temp2',
            new_name='group',
        ),
    ]
