# Generated by Django 3.2.13 on 2022-06-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_merge_20220610_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinplace',
            name='variant',
            field=models.ManyToManyField(to='catalog.ProductVariant'),
        ),
        migrations.AlterField(
            model_name='productinplace',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.variantgroup'),
        ),
    ]
