# Generated by Django 3.2.13 on 2022-06-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20220620_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductvariant',
            name='variant_group',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_group',
        ),
    ]
