# Generated by Django 3.2.13 on 2022-06-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20220620_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrate',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
    ]
