# Generated by Django 3.2.13 on 2022-06-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_productrate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrate',
            name='comment',
            field=models.TextField(default='', verbose_name='Komentarz'),
            preserve_default=False,
        ),
    ]
