# Generated by Django 3.2.13 on 2022-07-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20220712_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Krótki opis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Krótki opis'),
        ),
    ]
