# Generated by Django 3.2.13 on 2022-07-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20220712_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='net_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Cena netto'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='vat_base',
            field=models.FloatField(blank=True, null=True, verbose_name='VAT'),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Cena netto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='similar_products',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.Product', verbose_name='Podobne produkty'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_base',
            field=models.FloatField(blank=True, null=True, verbose_name='VAT'),
        ),
    ]
