# Generated by Django 3.2.13 on 2022-07-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20220713_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='C:\\Projects\\piekarnia\\PiekarniaBatog\\src\\piekarniaApi\\media', verbose_name='Obraz'),
        ),
    ]
