# Generated by Django 3.2.13 on 2022-07-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductvariant',
            name='delivery_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Czas dostawy'),
        ),
        migrations.AlterField(
            model_name='historicalproductvariant',
            name='extra_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Dodatkowa opłata'),
        ),
        migrations.AlterField(
            model_name='historicalproductvariant',
            name='stock',
            field=models.FloatField(blank=True, null=True, verbose_name='Ilość sztuk'),
        ),
        migrations.AlterField(
            model_name='historicalproductvariant',
            name='unit',
            field=models.IntegerField(choices=[(0, 'szt.'), (1, 'kg.'), (2, 'kpl.'), (3, 'l')], default=0, verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='historicalproductvariant',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Waga'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='delivery_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Czas dostawy'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='extra_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Dodatkowa opłata'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.FloatField(blank=True, null=True, verbose_name='Ilość sztuk'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='unit',
            field=models.IntegerField(choices=[(0, 'szt.'), (1, 'kg.'), (2, 'kpl.'), (3, 'l')], default=0, verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Waga'),
        ),
    ]
