# Generated by Django 3.2.13 on 2022-10-03 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20220712_1238'),
        ('catalog', '0021_auto_20220714_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductimage',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Obraz'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Obraz'),
        ),
        migrations.CreateModel(
            name='CategoryInPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
        ),
    ]
