# Generated by Django 3.2.13 on 2022-10-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20221003_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='nutrition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nutrition',
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.ProductNutrition', verbose_name='Wartości odżywcze'),
        ),
    ]
