# Generated by Django 3.2.13 on 2022-10-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20221003_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True, verbose_name='Węglowodany'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='fat',
            field=models.FloatField(blank=True, null=True, verbose_name='Tłuszcze'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='fatty_acids',
            field=models.FloatField(blank=True, null=True, verbose_name='Kwasy tłuszczowe'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='fiber',
            field=models.FloatField(blank=True, null=True, verbose_name='Błonnik'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='nutrition',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Wartości odżywcze'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='protein',
            field=models.FloatField(blank=True, null=True, verbose_name='Białko'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='salt',
            field=models.FloatField(blank=True, null=True, verbose_name='Sól'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='sugar',
            field=models.FloatField(blank=True, null=True, verbose_name='Cukry'),
        ),
        migrations.AddField(
            model_name='product',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True, verbose_name='Węglowodany'),
        ),
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.FloatField(blank=True, null=True, verbose_name='Tłuszcze'),
        ),
        migrations.AddField(
            model_name='product',
            name='fatty_acids',
            field=models.FloatField(blank=True, null=True, verbose_name='Kwasy tłuszczowe'),
        ),
        migrations.AddField(
            model_name='product',
            name='fiber',
            field=models.FloatField(blank=True, null=True, verbose_name='Błonnik'),
        ),
        migrations.AddField(
            model_name='product',
            name='protein',
            field=models.FloatField(blank=True, null=True, verbose_name='Białko'),
        ),
        migrations.AddField(
            model_name='product',
            name='salt',
            field=models.FloatField(blank=True, null=True, verbose_name='Sól'),
        ),
        migrations.AddField(
            model_name='product',
            name='sugar',
            field=models.FloatField(blank=True, null=True, verbose_name='Cukry'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='nutrition',
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Wartości odżywcze'),
        ),
        migrations.DeleteModel(
            name='ProductNutrition',
        ),
    ]
