# Generated by Django 3.2.13 on 2022-10-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20221003_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
    ]
