# Generated by Django 3.2.13 on 2022-10-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20221025_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='product_code',
            field=models.CharField(default=0, max_length=128, verbose_name='Kod produktu'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=0, max_length=128, verbose_name='Kod produktu'),
        ),
    ]
