# Generated by Django 3.2.13 on 2022-06-14 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20220613_1036'),
        ('order', '0005_alter_cardproductvariant_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardproductvariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productinplace'),
        ),
    ]
