# Generated by Django 3.2.13 on 2022-06-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_cardproductvariant_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardproductvariant',
            name='selected_variant',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
