# Generated by Django 3.2.13 on 2022-06-24 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220609_1255'),
        ('order', '0008_alter_cardproductvariant_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'oczekiwanie na płatność'), (1, 'opłacono'), (2, 'w realizacji'), (3, 'zrealizowane')], default=0)),
                ('payment_status', models.IntegerField(choices=[(0, 'Oczekuje na płatność'), (1, 'Opłacono'), (2, 'Anulowano')], default=0)),
                ('is_repeated', models.BooleanField(default=False)),
                ('delivery_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.deliverytype')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.paymenttype')),
                ('product_variant', models.ManyToManyField(to='order.CardProductVariant')),
            ],
        ),
        migrations.CreateModel(
            name='RepeatedDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=32)),
                ('day_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderRepeatability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=64)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderdetails')),
                ('repeated_days', models.ManyToManyField(to='order.RepeatedDays')),
            ],
        ),
        migrations.CreateModel(
            name='OrderIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.IntegerField(choices=[(0, 'Uszkodzony produkt'), (1, 'Problem z dostawą'), (2, 'Niepełne zamówienie')], default=0)),
                ('custom_issue_type', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(verbose_name='Opis zgłoszenia')),
                ('status', models.IntegerField(choices=[(0, 'Oczekuje na rozpatrzenie'), (1, 'Rozpatrzono')], default=0)),
                ('issue_images', models.ManyToManyField(to='order.IssueImage')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderdetails')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('invoice', models.FileField(upload_to='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderdetails')),
            ],
        ),
    ]
