# Generated by Django 3.2.13 on 2022-06-27 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220609_1255'),
        ('order', '0009_issueimage_orderdetails_orderinvoice_orderissue_orderrepeatability_repeateddays'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='delivery_address',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, to='core.clientaddress'),
            preserve_default=False,
        ),
    ]
