# Generated by Django 3.2.13 on 2022-06-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_orderdetails_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrepeatability',
            name='frequency',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='orderrepeatability',
            name='repeated_days',
            field=models.ManyToManyField(blank=True, null=True, to='order.RepeatedDays'),
        ),
    ]
