# Generated by Django 3.2.13 on 2022-06-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20220627_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='product_variant',
            new_name='products',
        ),
    ]
