# Generated by Django 3.2.13 on 2022-06-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_rename_product_variant_orderdetails_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='order_price',
            field=models.FloatField(default=125),
            preserve_default=False,
        ),
    ]
