# Generated by Django 3.2.13 on 2022-06-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20220628_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='products_quantity',
        ),
        migrations.AlterField(
            model_name='orderissue',
            name='status',
            field=models.IntegerField(choices=[(0, 'Oczekuje na rozpatrzenie'), (1, 'Rozpatrzone')], default=0),
        ),
    ]
