# Generated by Django 3.2.13 on 2022-06-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20220628_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'oczekuje na płatność'), (1, 'odrzucono'), (2, 'opłacono'), (3, 'anulowano')], default=0),
        ),
        migrations.AlterField(
            model_name='orderissue',
            name='status',
            field=models.IntegerField(choices=[(0, 'oczekuje na rozpatrzenie'), (1, 'rozpatrzone')], default=0),
        ),
    ]
