# Generated by Django 3.2.13 on 2022-06-30 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20220629_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinvoice',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='grossPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='netPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='status',
            field=models.IntegerField(choices=[(0, 'zlecono wystawienie'), (1, 'wystawiono')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderinvoice',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orderinvoice',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
