# Generated by Django 3.2.13 on 2022-06-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20220630_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinvoice',
            old_name='createDate',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='orderinvoice',
            old_name='grossPrice',
            new_name='gross_price',
        ),
        migrations.RenameField(
            model_name='orderinvoice',
            old_name='netPrice',
            new_name='net_price',
        ),
    ]
