# Generated by Django 3.2.13 on 2022-06-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20220630_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinvoice',
            name='order',
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='orders',
            field=models.ManyToManyField(to='order.OrderDetails'),
        ),
    ]
