# Generated by Django 3.2.13 on 2022-06-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20220630_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinvoice',
            name='status',
            field=models.IntegerField(choices=[(0, 'zlecono wystawienie'), (1, 'wystawiono')], default=0),
        ),
    ]
