# Generated by Django 3.2.13 on 2022-06-30 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220609_1255'),
        ('order', '0021_alter_orderinvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='client',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.DO_NOTHING, to='core.client'),
            preserve_default=False,
        ),
    ]
