# Generated by Django 3.2.13 on 2022-07-01 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220609_1255'),
        ('order', '0022_orderdetails_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.clientaddress'),
        ),
    ]
