# Generated by Django 3.2.13 on 2022-07-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_orderdetails_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='has_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
