# Generated by Django 3.2.13 on 2022-07-05 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0027_orderissueconversation_orderissuemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderissueconversation',
            name='author',
        ),
        migrations.AddField(
            model_name='orderissuemessage',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
    ]
