# Generated by Django 3.2.13 on 2022-07-06 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_alter_orderissuemessage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
