# Generated by Django 3.2.13 on 2022-09-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_orderdetails_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderissue',
            name='issue_type',
            field=models.IntegerField(choices=[(1, 'Uszkodzony produkt'), (2, 'Problem z dostawą'), (3, 'Niepełne zamówienie'), (4, 'Błędne dane'), (5, 'Inne... (własne)')], default=0),
        ),
    ]
