# Generated by Django 3.2.13 on 2022-10-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_alter_orderissue_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'oczekuje na płatność'), (1, 'odrzucono'), (2, 'opłacono'), (3, 'anulowano'), (4, 'płatność przy odbiorze')], default=0),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.IntegerField(choices=[(0, 'oczekiwanie na płatność'), (1, 'opłacono'), (2, 'w realizacji'), (3, 'zrealizowane'), (4, 'gotowe do odbioru')], default=0),
        ),
    ]
