# Generated by Django 3.2.13 on 2022-10-04 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_auto_20221003_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderissue',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderdetails'),
        ),
        migrations.AlterField(
            model_name='orderissueconversation',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderissue'),
        ),
        migrations.AlterField(
            model_name='orderrepeatability',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderdetails'),
        ),
    ]
