# Generated by Django 3.2.13 on 2022-10-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_auto_20221004_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='notes_for_order',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
