# Generated by Django 3.2.13 on 2022-10-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_orderdetails_notes_for_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='notes_for_order',
            field=models.TextField(default=''),
        ),
    ]
