# Generated by Django 3.2.13 on 2022-10-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_alter_orderdetails_notes_for_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='order_id',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
