# Generated by Django 3.2.12 on 2022-11-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_orderdetails_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.IntegerField(choices=[(0, 'oczekiwanie na płatność'), (1, 'opłacono'), (2, 'w realizacji'), (3, 'zrealizowane'), (4, 'gotowe do odbioru'), (5, 'wydano')], default=0),
        ),
    ]
