# Generated by Django 3.2.18 on 2023-04-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_alter_orderdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='delivery_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
